print("Bienvemido al comparador de fechas")
print("Primera fecha:")
day1 = int(input("Día: "))
month1 = int(input("Mes: "))
year1 = int(input("Año: "))
print("Segunda fecha:")
day2 = int(input("Día: "))
month2 = int(input("Mes: "))
year2 = int(input("Año: "))
